import Head from 'next/head'
import { Inter } from 'next/font/google'
import { BsFillMoonStarsFill } from "react-icons/bs";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>George's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className='bg-blue-300 px-10'>
        <div className='min-h-screen'>
          <section>
            <nav className='py-10 mb-20 flex justify-between'>
              <h1 className='text-2xl'>George Dodd</h1>
              <ul className='flex items-center'>
                <li>
                  <BsFillMoonStarsFill className='cursor-pointer text-3xl' />

                </li>
                <li><a href="https://www.linkedin.com/in/george-dodd-irwin-b6a11a242/"> LinkedIn </a> </li>

              </ul>
            </nav>
          </section>

        </div>
      </main>
    </>
  )
}
