import { NextPage } from "next";
import Head from 'next/head'
import { AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube, AiFillGithub } from "react-icons/ai";

const projects: NextPage = () => {

    return (
        <>
            <Head>
                <title>George's Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className='bg-blue-300 px-10'>
                <div className='min-h-screen'>
                    <section>
                        <nav className='py-10 mb-20 flex justify-between'>
                            <h1 className='text-2xl font-'>   DoddDigitals</h1>
                            <ul className='flex items-center'>
                                <li>
                                </li>
                                <li> <a className='bg-gray-800 text-white px-3 py-2 rounded-lg ml-2' href="/"> Home </a> </li>
                                <li> <a className='bg-gray-600 text-white px-3 py-2 rounded-lg ml-2' href="/skills"> Skills </a> </li>
                                <li> <a className='bg-gray-600 text-white px-3 py-2 rounded-lg ml-2' href="/projects"> Projects </a> </li>
                                <li> <a className='bg-gray-600 text-white px-3 py-2 rounded-lg ml-2' href="/contact"> Contact </a> </li>
                            </ul>
                        </nav>

                        <div className=' text-center p-10'>
                            <h2 className='text-5xl py-2 text-gray-600 font-medium'>
                                George's Portfolio Page
                            </h2>
                            <h3 className='text-2xl py-2'>Designer, Creator and Crypto Enthusiast</h3>
                        </div>
                    </section>

                    <section>
                        <section>
                            <div>
                                <h3 className="text-center text-3xl py-2"> Examples of my work</h3>
                                <p className="text-center text-md py-2 leading-8 text-gray-900">

                                </p>
                            </div>
                        </section>
                    </section>
                    <section>
                            <div className="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
                                <h2 className="text-2xl font-bold tracking-tight text-gray-900">Customers also purchased</h2>

                                <div className="mt-6 grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
                                    <div className="group relative">
                                        <div className="min-h-80 aspect-w-1 aspect-h-1 w-full overflow-hidden rounded-md bg-gray-200 group-hover:opacity-75 lg:aspect-none lg:h-80">
                                        </div>
                                        <div className="mt-4 flex justify-between">
                                            <div>
                                                <h3 className="text-sm text-gray-700">
                                                    <a href="#">
                                                        <span aria-hidden="true" className="absolute inset-0"></span>
                                                        Basic Tee
                                                    </a>
                                                </h3>
                                                <p className="mt-1 text-sm text-gray-500">Black</p>
                                            </div>
                                            <p className="text-sm font-medium text-gray-900">$35</p>
                                        </div>
                                    </div>
                                    


                                </div>
                            </div>
                    </section>
                </div>
            </main>
        </>
    )
}

export default projects; 